import type { Metadata } from "next";
import { Style_Script } from "next/font/google";
import "./globals.css";

const styleScript = Style_Script({
  weight: "400",
  variable: "--font-script",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LogiTrace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${styleScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
